<?php
declare(strict_types=1);

/**
 * Generates migrations/seeds/100_demo_data.sql (deterministic).
 *   php tools/generate_seed.php
 *
 * Demo data: departments, designations, shifts, shift groups, holidays, 15 employees with
 * salary history, demo users per role, September 2026 daily attendance (+ raw machine punches),
 * and unprocessed punches for 2026-10-01 to test Daily Attendance Post.
 */

mt_srand(20260901);

$out = [];
$q = static fn(?string $s): string => $s === null ? 'NULL' : "'" . str_replace(["\\", "'"], ["\\\\", "''"], $s) . "'";
$row = static fn(array $vals): string => '(' . implode(', ', array_map(
    fn($v) => is_int($v) || is_float($v) ? (string)$v : $q($v),
    $vals
)) . ')';

$out[] = "-- Demo data generated by tools/generate_seed.php - do not edit by hand.";
$out[] = "-- Demo users (password for all: demo1234): hr, operator, accounts, viewer";
$hash = '$2y$10$4fjYdiUfRiG.UCvIvhqQ9.0sXbzqJBkjnn9F8EWZNKImYJYMEmQJS';
$out[] = "INSERT INTO users (username, full_name, password_hash, role_id) VALUES\n " . implode(",\n ", [
    $row(['hr', 'Ayesha Malik (HR)', $hash, 2]),
    $row(['operator', 'Bilal Ahmed (Attendance)', $hash, 3]),
    $row(['accounts', 'Usman Ghani (Accounts)', $hash, 4]),
    $row(['viewer', 'Guest Viewer', $hash, 5]),
]) . ';';

$out[] = "UPDATE settings SET setting_value = '\"Al-Noor Textile Mills (Pvt) Ltd\"' WHERE setting_key = 'company_name';";
$out[] = "UPDATE settings SET setting_value = '\"النور ٹیکسٹائل ملز (پرائیویٹ) لمیٹڈ\"' WHERE setting_key = 'company_name_ur';";
$out[] = "UPDATE settings SET setting_value = '\"Plot 21, Sundar Industrial Estate, Raiwind Road, Lahore\"' WHERE setting_key = 'company_address';";
$out[] = "UPDATE settings SET setting_value = '\"042-35970000\"' WHERE setting_key = 'company_phone';";

$depts = [
    ['WEAV', 'Weaving', 'بنائی'], ['SPIN', 'Spinning', 'کتائی'], ['STCH', 'Stitching', 'سلائی'],
    ['FIN', 'Finishing', 'فنشنگ'], ['DYE', 'Dyeing', 'رنگائی'], ['ADM', 'Administration', 'انتظامیہ'],
];
$out[] = "INSERT INTO departments (id, code, name, name_ur) VALUES\n " . implode(",\n ",
    array_map(fn($d, $i) => $row([$i + 1, ...$d]), $depts, array_keys($depts))) . ';';

$desigs = [
    ['MGR', 'Manager', 'منیجر'], ['SUP', 'Supervisor', 'سپروائزر'], ['OPR', 'Machine Operator', 'مشین آپریٹر'],
    ['HLP', 'Helper', 'ہیلپر'], ['WVR', 'Weaver', 'جولاہا'], ['STC', 'Stitcher', 'درزی'],
    ['CLK', 'Clerk', 'کلرک'], ['GRD', 'Security Guard', 'چوکیدار'],
];
$out[] = "INSERT INTO designations (id, code, name, name_ur) VALUES\n " . implode(",\n ",
    array_map(fn($d, $i) => $row([$i + 1, ...$d]), $desigs, array_keys($desigs))) . ';';

// id, code, name, start, end, overnight, break, grace, halfday, min_ot, duration
$shifts = [
    1 => ['G', 'General 09-17',  '09:00:00', '17:00:00', 0, 60, 10, 210, 30, 420],
    2 => ['D', 'Day 08-20',      '08:00:00', '20:00:00', 0, 60, 10, 330, 30, 660],
    3 => ['N', 'Night 20-08',    '20:00:00', '08:00:00', 1, 60, 10, 330, 30, 660],
];
$out[] = "INSERT INTO shifts (id, code, name, start_time, end_time, is_overnight, break_minutes, grace_minutes, half_day_minutes, min_ot_minutes, duration_minutes) VALUES\n "
    . implode(",\n ", array_map(fn($s, $id) => $row([$id, ...$s]), $shifts, array_keys($shifts))) . ';';

$out[] = "INSERT INTO shift_groups (id, code, name, rest_days, remarks) VALUES\n "
    . implode(",\n ", [
        $row([1, 'GEN', 'General Staff', null, 'Office / general shift, company rest day']),
        $row([2, 'ROT-A', 'Rotation A (Day/Night weekly)', null, 'Day shift 7 days then Night shift 7 days']),
        $row([3, 'ROT-B', 'Rotation B (Night/Day weekly)', null, 'Opposite of Rotation A']),
    ]) . ';';
$out[] = "INSERT INTO shift_group_steps (shift_group_id, seq, shift_id, days) VALUES (1, 1, 1, 7), (2, 1, 2, 7), (2, 2, 3, 7), (3, 1, 3, 7), (3, 2, 2, 7);";

$holidays = [
    ['2026-02-05', 'Kashmir Solidarity Day', 'یوم یکجہتی کشمیر', 'gazetted'],
    ['2026-03-21', 'Eid-ul-Fitr', 'عید الفطر', 'gazetted'],
    ['2026-03-22', 'Eid-ul-Fitr (2nd day)', 'عید الفطر', 'gazetted'],
    ['2026-03-23', 'Pakistan Day', 'یوم پاکستان', 'gazetted'],
    ['2026-05-01', 'Labour Day', 'یوم مزدور', 'gazetted'],
    ['2026-05-27', 'Eid-ul-Azha', 'عید الاضحیٰ', 'gazetted'],
    ['2026-05-28', 'Youm-e-Takbeer / Eid-ul-Azha', 'یوم تکبیر', 'gazetted'],
    ['2026-06-25', 'Ashura (9th Muharram)', 'عاشورہ', 'gazetted'],
    ['2026-06-26', 'Ashura (10th Muharram)', 'عاشورہ', 'gazetted'],
    ['2026-08-14', 'Independence Day', 'یوم آزادی', 'gazetted'],
    ['2026-08-26', 'Eid Milad-un-Nabi', 'عید میلاد النبی', 'gazetted'],
    ['2026-09-12', 'Annual Mill Maintenance Day', 'سالانہ مرمت', 'company'],
    ['2026-11-09', 'Iqbal Day', 'یوم اقبال', 'gazetted'],
    ['2026-12-25', 'Quaid-e-Azam Day', 'یوم قائداعظم', 'gazetted'],
];
$out[] = "-- Islamic holiday dates are approximate (moon sighting); adjust each year.";
$out[] = "INSERT INTO holidays (holiday_date, name, name_ur, holiday_type) VALUES\n "
    . implode(",\n ", array_map($row, $holidays)) . ';';

// code, name, name_ur, father, father_ur, relation, gender, dept, desig, type, join, group, shift_date, status, leaving, basic, daily, city, increment(basic or daily)
$emps = [
    ['0001', 'Muhammad Aslam',     'محمد اسلم',      'Ghulam Rasool',   'غلام رسول',    'S/O', 'M', 6, 1, 'permanent',   '2015-03-01', 1, '2015-03-01', 'active', null, 145000, 0,    'Lahore',     160000],
    ['0002', 'Rashid Mehmood',     'راشد محمود',     'Abdul Majeed',    'عبدالمجید',    'S/O', 'M', 1, 2, 'permanent',   '2017-06-15', 2, '2026-08-30', 'active', null, 72000,  0,    'Lahore',     80000],
    ['0003', 'Shahid Iqbal',       'شاہد اقبال',     'Muhammad Iqbal',  'محمد اقبال',   'S/O', 'M', 1, 5, 'permanent',   '2019-01-10', 2, '2026-08-30', 'active', null, 45000,  0,    'Kasur',      null],
    ['0004', 'Naveed Akhtar',      'نوید اختر',      'Akhtar Ali',      'اختر علی',     'S/O', 'M', 1, 5, 'permanent',   '2020-09-01', 3, '2026-08-30', 'active', null, 43000,  0,    'Lahore',     null],
    ['0005', 'Zahid Hussain',      'زاہد حسین',      'Fazal Hussain',   'فضل حسین',     'S/O', 'M', 2, 3, 'permanent',   '2018-04-20', 2, '2026-08-30', 'active', null, 48000,  0,    'Sheikhupura', 52000],
    ['0006', 'Imran Khan',         'عمران خان',      'Sher Khan',       'شیر خان',      'S/O', 'M', 2, 3, 'permanent',   '2021-02-01', 3, '2026-08-30', 'active', null, 42000,  0,    'Lahore',     null],
    ['0007', 'Kashif Ali',         'کاشف علی',       'Liaqat Ali',      'لیاقت علی',    'S/O', 'M', 2, 4, 'daily_wages', '2024-11-05', 1, '2024-11-05', 'active', null, 0,      1500, 'Raiwind',    null],
    ['0008', 'Sajida Parveen',     'ساجدہ پروین',    'Muhammad Ashraf', 'محمد اشرف',    'W/O', 'F', 3, 6, 'permanent',   '2016-08-08', 1, '2016-08-08', 'active', null, 46000,  0,    'Lahore',     50000],
    ['0009', 'Nasreen Bibi',       'نسرین بی بی',    'Allah Ditta',     'اللہ دتہ',     'D/O', 'F', 3, 6, 'permanent',   '2022-03-15', 1, '2022-03-15', 'active', null, 40000,  0,    'Lahore',     null],
    ['0010', 'Rubina Kausar',      'روبینہ کوثر',    'Nazir Ahmed',     'نذیر احمد',    'W/O', 'F', 3, 6, 'daily_wages', '2025-01-20', 1, '2025-01-20', 'active', null, 0,      1450, 'Kasur',      null],
    ['0011', 'Tariq Mehmood',      'طارق محمود',     'Sardar Muhammad', 'سردار محمد',   'S/O', 'M', 4, 2, 'permanent',   '2014-11-01', 1, '2014-11-01', 'active', null, 68000,  0,    'Lahore',     75000],
    ['0012', 'Asif Raza',          'آصف رضا',        'Raza Muhammad',   'رضا محمد',     'S/O', 'M', 4, 4, 'daily_wages', '2026-09-14', 1, '2026-09-14', 'active', null, 0,      1400, 'Lahore',     null],
    ['0013', 'Waqas Ahmad',        'وقاص احمد',      'Bashir Ahmad',    'بشیر احمد',    'S/O', 'M', 5, 3, 'contract',    '2025-07-01', 2, '2026-08-30', 'active', null, 44000,  0,    'Lahore',     null],
    ['0014', 'Faisal Nawaz',       'فیصل نواز',      'Haq Nawaz',       'حق نواز',      'S/O', 'M', 5, 4, 'permanent',   '2023-05-02', 3, '2026-08-30', 'inactive', '2026-09-20', 39000, 0, 'Okara',  null],
    ['0015', 'Muhammad Akram',     'محمد اکرم',      'Noor Muhammad',   'نور محمد',     'S/O', 'M', 6, 8, 'permanent',   '2012-01-01', 1, '2012-01-01', 'active', null, 40000,  0,    'Lahore',     null],
];

$empRows = [];
$salRows = [];
foreach ($emps as $i => $e) {
    $id = $i + 1;
    [$code, $name, $nameUr, $father, $fatherUr, $rel, $gender, $dept, $desig, $type, $join, $group, $sdate, $status, $leaving, $basic, $daily, $city, $inc] = $e;
    $cnic = sprintf('35202-%07d-%d', 1234500 + $id * 731, $gender === 'F' ? 2 * ($id % 4) + 2 : 2 * ($id % 4) + 1);
    $dob = sprintf('%d-%02d-%02d', 1970 + ($id * 3) % 30, ($id % 12) + 1, ($id * 7) % 27 + 1);
    $cell = sprintf('03%02d-%07d', [0, 1, 2, 3, 21, 33, 45][$id % 7], 4500000 + $id * 1379);
    $empRows[] = $row([$id, $code, $name, $nameUr, $rel, $father, $fatherUr, $gender,
        'House ' . (10 + $id) . ', Street ' . (2 + $id % 9) . ', Mohallah ' . ['Islampura', 'Gulshan Colony', 'Model Town', 'Rehmanpura'][$id % 4], $city, $dob, $cell,
        $cnic, $dept, $desig, $type, $join, $leaving, $group, $sdate, $status, $id, ['Matric', 'Middle', 'F.A', 'B.A', 'Primary'][$id % 5]]);
    $eobi = $type === 'permanent' ? 1 : 0;
    $bank = $basic >= 60000;
    $salRows[] = $row([$id, $join, $basic, $daily, 0, 1, $eobi, $eobi, $basic >= 100000 ? 1 : 0,
        $bank ? 'bank' : 'cash', $bank ? 'Meezan Bank' : null, $bank ? sprintf('0201%010d', 7000000 + $id) : null, 'Appointment']);
    if ($inc) {
        $salRows[] = $row([$id, '2026-07-01', $inc, 0, 0, 1, $eobi, $eobi, $inc >= 100000 ? 1 : 0,
            $bank ? 'bank' : 'cash', $bank ? 'Meezan Bank' : null, $bank ? sprintf('0201%010d', 7000000 + $id) : null, 'Annual Increment']);
    }
}
$out[] = "INSERT INTO employees (id, code, name, name_ur, relation, father_name, father_name_ur, gender, address, city, dob, cell, cnic, department_id, designation_id, emp_type, joining_date, leaving_date, shift_group_id, shift_date, status, machine_id, qualification) VALUES\n "
    . implode(",\n ", $empRows) . ';';
$out[] = "INSERT INTO employee_salary_history (employee_id, effective_from, basic_salary, daily_rate, allowances, ot_applicable, eobi_applicable, pessi_applicable, tax_applicable, payment_mode, bank_name, bank_account, reason) VALUES\n "
    . implode(",\n ", $salRows) . ';';
$out[] = "INSERT INTO employee_qualifications (employee_id, degree, institute, passing_year, grade) VALUES (1, 'MBA', 'University of the Punjab', 2010, 'A'), (1, 'B.Com', 'Hailey College of Commerce', 2007, 'B'), (11, 'DAE Textile', 'Govt. College of Technology, Faisalabad', 2008, 'A');";
$out[] = "INSERT INTO employee_experiences (employee_id, organization, designation, from_date, to_date, reason_left) VALUES (1, 'Sapphire Textile Mills', 'Assistant Manager', '2010-07-01', '2015-02-15', 'Better opportunity'), (2, 'Kohinoor Mills', 'Weaver', '2012-01-01', '2017-05-31', 'Relocation');";

// ---------------------------------------------------------------- attendance: September 2026
$holidaySet = array_column($holidays, 0);
$shiftFor = static function (int $group, string $anchor, string $date): int {
    $rot = [1 => [[1, 7]], 2 => [[2, 7], [3, 7]], 3 => [[3, 7], [2, 7]]][$group];
    $total = array_sum(array_column($rot, 1));
    $diff = (int)((strtotime($date) - strtotime($anchor)) / 86400);
    $pos = (($diff % $total) + $total) % $total;
    foreach ($rot as [$sid, $days]) {
        if ($pos < $days) {
            return $sid;
        }
        $pos -= $days;
    }
    return $rot[0][0];
};
$fmt = static fn(int $ts): string => date('Y-m-d H:i:s', $ts);

$attRows = [];
$punchRows = [];
for ($d = 1; $d <= 30; $d++) {
    $date = sprintf('2026-09-%02d', $d);
    $dow = (int)date('w', strtotime($date));
    foreach ($emps as $i => $e) {
        $id = $i + 1;
        [, , , , , , , , , $type, $join, $group, $sdate, , $leaving] = $e;
        if ($leaving && $date > $leaving) {
            continue;
        }
        $shiftId = $shiftFor($group, $sdate, $date);
        [, , $st, $en, $overnight, $break, $grace, $half, $minOt, $dur] = $shifts[$shiftId];
        $in = $out2 = null;
        $work = $late = $early = $ot = 0;
        $source = 'manual';

        if ($date < $join) {
            $status = 'O';
        } elseif ($date === $join) {
            $status = 'S';
        } elseif (in_array($date, $holidaySet, true)) {
            $status = 'H';
        } elseif ($dow === 0) {
            $status = 'R';
        } else {
            $r = mt_rand(1, 100);
            $status = match (true) {
                $r <= 5  => 'A',
                $r <= 8  => 'L',
                $r <= 9  => 'LW',
                $r <= 11 => 'HD',
                default  => 'P',
            };
        }
        if (in_array($status, ['P', 'HD', 'S'], true)) {
            $source = 'machine';
            $startTs = strtotime("$date $st");
            $endTs = strtotime("$date $en") + ($overnight ? 86400 : 0);
            $lateBy = mt_rand(1, 100) <= 15 ? mt_rand(11, 45) : mt_rand(-15, 8);
            $inTs = $startTs + $lateBy * 60;
            if ($status === 'HD') {
                $outTs = $startTs + intdiv($dur, 2) * 60 + mt_rand(0, 20) * 60;
            } else {
                $extra = mt_rand(1, 100) <= 25 ? mt_rand(30, 150) : mt_rand(-10, 15);
                $outTs = $endTs + $extra * 60;
            }
            $in = $fmt($inTs);
            $out2 = $fmt($outTs);
            $elapsed = intdiv($outTs - $inTs, 60);
            $work = max(0, $elapsed - ($elapsed > $break + 60 ? $break : 0));
            $late = ($inTs - $startTs) / 60 > $grace ? intdiv($inTs - $startTs, 60) : 0;
            $early = $outTs < $endTs ? intdiv($endTs - $outTs, 60) : 0;
            $extraMin = intdiv($outTs - $endTs, 60);
            $ot = ($status === 'P' && $extraMin >= $minOt) ? $extraMin : 0;
            if ($status === 'P' && $half > 0 && $work < $half) {
                $status = 'HD';
            }
            $punchRows[] = $row([$id, $id, $in, 0, 1, 'machine', "M$id", 'DEMO0001', 1]);
            $punchRows[] = $row([$id, $id, $out2, 1, 1, 'machine', "M$id", 'DEMO0001', 1]);
        }
        $attRows[] = $row([$id, $date, $shiftId, $status, $in, $out2, $work, $late, $early, $ot, $source]);
    }
}
foreach (array_chunk($attRows, 100) as $chunk) {
    $out[] = "INSERT INTO attendance_daily (employee_id, att_date, shift_id, status, time_in, time_out, work_minutes, late_minutes, early_minutes, ot_minutes, source) VALUES\n "
        . implode(",\n ", $chunk) . ';';
}

// Unprocessed punches for 2026-10-01 (to test Daily Attendance Post in batch 2)
foreach ($emps as $i => $e) {
    $id = $i + 1;
    if ($e[13] !== 'active' || $id % 6 === 0) {
        continue; // id 6 and 12 absent
    }
    $shiftId = $shiftFor($e[11], $e[12], '2026-10-01');
    [, , $st, $en, $overnight] = $shifts[$shiftId];
    $inTs = strtotime("2026-10-01 $st") + mt_rand(-12, 25) * 60;
    $punchRows[] = $row([$id, $id, $fmt($inTs), 0, 1, 'machine', "M$id", 'DEMO0001', 0]);
    if (!$overnight && $id !== 9) { // employee 9 forgot to punch out
        $outTs = strtotime("2026-10-01 $en") + mt_rand(-5, 90) * 60;
        $punchRows[] = $row([$id, $id, $fmt($outTs), 1, 1, 'machine', "M$id", 'DEMO0001', 0]);
    }
}
$out[] = "INSERT INTO devices (serial_no, name, location) VALUES ('DEMO0001', 'Main Gate ZK', 'Main gate');";
foreach (array_chunk($punchRows, 150) as $chunk) {
    $out[] = "INSERT INTO attendance_punches (machine_id, employee_id, punch_time, punch_state, verify_mode, source, person_key, device_sn, is_processed) VALUES\n "
        . implode(",\n ", $chunk) . ';';
}

$file = dirname(__DIR__) . '/migrations/seeds/100_demo_data.sql';
file_put_contents($file, implode("\n\n", $out) . "\n");
echo "Wrote $file (" . count($attRows) . " attendance rows, " . count($punchRows) . " punches)\n";
