<?php
declare(strict_types=1);

/**
 * Server-side messages in English and Urdu. The SPA sends X-Lang on every
 * request, so validation messages appear beside fields in the user's language.
 */
final class Lang
{
    private static ?string $lang = null;

    private const MESSAGES = [
        'en' => [
            'validation.failed'        => 'Please correct the highlighted fields.',
            'validation.required'      => 'This field is required.',
            'validation.string'        => 'Must be text.',
            'validation.max'           => 'Must be at most :max characters.',
            'validation.min'           => 'Must be at least :min characters.',
            'validation.min_value'     => 'Must be at least :min.',
            'validation.max_value'     => 'Must be at most :max.',
            'validation.integer'       => 'Must be a whole number.',
            'validation.numeric'       => 'Must be a number.',
            'validation.email'         => 'Enter a valid email address.',
            'validation.in'            => 'Select a valid option.',
            'validation.date'          => 'Enter a valid date (YYYY-MM-DD).',
            'validation.bool'          => 'Must be yes or no.',
            'validation.regex'         => 'Invalid format.',
            'validation.username'      => 'Use 3–50 letters, digits, dot, dash or underscore.',
            'validation.unique'        => 'This value is already in use.',
            'validation.exists'        => 'Selected record does not exist.',
            'validation.confirmed'     => 'Passwords do not match.',
            'validation.password'      => 'Password must be at least 8 characters and contain letters and numbers.',
            'validation.password_same' => 'New password must be different from the current one.',
            'auth.invalid'             => 'Invalid username or password.',
            'auth.inactive'            => 'Your account is inactive. Contact the administrator.',
            'auth.locked'              => 'Too many failed attempts. Try again in :minutes minutes.',
            'auth.required'            => 'Please log in to continue.',
            'auth.expired'             => 'Your session has expired. Please log in again.',
            'auth.current_wrong'       => 'Current password is incorrect.',
            'auth.must_change'         => 'You must change your password before continuing.',
            'auth.password_changed'    => 'Password changed successfully.',
            'auth.logged_out'          => 'Logged out.',
            'csrf.invalid'             => 'Security token expired. Please retry.',
            'error.forbidden'          => 'You do not have permission to do this.',
            'error.not_found'          => 'Record not found.',
            'error.route_not_found'    => 'Unknown API endpoint.',
            'error.method'             => 'Method not allowed.',
            'error.server'             => 'Something went wrong on the server. Please try again.',
            'error.bad_json'           => 'Invalid request body.',
            'error.constraint'         => 'This record is linked to other data or is a duplicate.',
            'error.db_not_configured'  => 'Database is not configured. Copy config.sample.php to the private folder as config.php.',
            'error.db_unavailable'     => 'Database is unavailable. Please try again shortly.',
            'setup.done'               => 'Setup already completed.',
            'setup.bad_key'            => 'Setup key is incorrect.',
            'user.self_deactivate'     => 'You cannot deactivate or delete your own account.',
            'user.last_admin'          => 'At least one active Admin must remain.',
            'role.admin_locked'        => 'Admin permissions cannot be changed.',
            'master.in_use'            => 'This record is used in other records and cannot be deleted. Mark it inactive instead.',
            'unit.dimension_locked'    => 'Items already use this unit; its dimension cannot change.',
            'party.type_required'      => 'Tick at least one: customer, supplier or fabric owner.',
            'item.ink_unit'            => 'Ink must use a volume unit (liter or ml).',
            'item.fabric_unit'         => 'Fabric must use a length or weight unit.',
            'item.locked_by_stock'     => 'Stock entries exist for this item; type and unit cannot change.',
            'design.finished_item_type'=> 'Select a finished fabric item.',
            'design.duplicate_colour'  => 'This colour is already listed.',
            'design.duplicate_item'    => 'This item is already listed.',
            'design.ink_colour_mismatch' => 'This ink is a different colour.',
            'design.basis_required'    => 'Required to calculate ink ml per meter.',
            'design.bom_item_type'     => 'Only paper, chemical or other items (inks go in the ink table).',
            'upload.failed'            => 'Upload failed. Please choose the file again.',
            'upload.too_large'         => 'File is too large (maximum 15 MB).',
            'upload.bad_type'          => 'Only JPG, PNG or WEBP images are allowed.',
            'upload.too_many_pixels'   => 'Image is too large (maximum 60 megapixels).',
            'upload.storage'           => 'Could not store the file on the server.',
            'voucher.saved'            => 'Voucher :no saved.',
            'voucher.cancelled'        => 'Voucher :no cancelled.',
            'voucher.no_lines'         => 'Add at least one line.',
            'voucher.future_date'      => 'Date cannot be in the future.',
            'voucher.not_editable'     => 'This voucher is cancelled and cannot be changed.',
            'stock.insufficient'       => 'Only :available :unit of :item available in :warehouse:lot.',
            'stock.would_go_negative'  => 'Not allowed: stock of :item in :warehouse:lot would become negative (already used by later vouchers).',
            'stock.lot'                => 'lot',
            'stock.lot_required'       => 'Lot number is required for this item.',
            'transfer.same_warehouse'  => 'Choose a different warehouse than the source.',
            'consumption.no_fabric'    => 'Fabric is not issued here (use production vouchers).',
            'ink_load.not_ink'         => 'Select an ink item (liter or ml).',
            'ink_load.too_small'       => 'Quantity is too small for the ink unit.',
            'production.no_ink_item'   => 'No active ink item for colour :colour (add one in the Ink Master).',
            'production.fabric_type'   => 'Select a fabric item.',
            'production.grey_required' => 'Select a grey fabric item.',
            'production.no_conversion' => 'Cannot convert meters to this item\'s unit (set its GSM and width).',
            'production.no_fabric_line'=> 'Fabric is entered in the header, not as a material line.',
            'production.end_before_start' => 'End time is before start time.',
            'saved'                    => 'Saved successfully.',
            'deleted'                  => 'Deleted successfully.',
        ],
        'ur' => [
            'validation.failed'        => 'براہ کرم نشان زدہ خانے درست کریں۔',
            'validation.required'      => 'یہ خانہ ضروری ہے۔',
            'validation.string'        => 'متن درج کریں۔',
            'validation.max'           => 'زیادہ سے زیادہ :max حروف۔',
            'validation.min'           => 'کم از کم :min حروف۔',
            'validation.min_value'     => 'کم از کم :min ہونا چاہیے۔',
            'validation.max_value'     => 'زیادہ سے زیادہ :max ہونا چاہیے۔',
            'validation.integer'       => 'مکمل عدد درج کریں۔',
            'validation.numeric'       => 'عدد درج کریں۔',
            'validation.email'         => 'درست ای میل درج کریں۔',
            'validation.in'            => 'درست انتخاب کریں۔',
            'validation.date'          => 'درست تاریخ درج کریں۔',
            'validation.bool'          => 'ہاں یا نہیں منتخب کریں۔',
            'validation.regex'         => 'غلط فارمیٹ۔',
            'validation.username'      => '3 سے 50 انگریزی حروف، ہندسے، ڈاٹ، ڈیش یا انڈر اسکور۔',
            'validation.unique'        => 'یہ پہلے سے استعمال میں ہے۔',
            'validation.exists'        => 'منتخب ریکارڈ موجود نہیں۔',
            'validation.confirmed'     => 'پاس ورڈ مماثل نہیں۔',
            'validation.password'      => 'پاس ورڈ کم از کم 8 حروف کا ہو اور اس میں حروف اور ہندسے دونوں ہوں۔',
            'validation.password_same' => 'نیا پاس ورڈ پرانے سے مختلف ہونا چاہیے۔',
            'auth.invalid'             => 'یوزر نیم یا پاس ورڈ غلط ہے۔',
            'auth.inactive'            => 'آپ کا اکاؤنٹ غیر فعال ہے۔ ایڈمن سے رابطہ کریں۔',
            'auth.locked'              => 'بہت زیادہ ناکام کوششیں۔ :minutes منٹ بعد دوبارہ کوشش کریں۔',
            'auth.required'            => 'جاری رکھنے کے لیے لاگ اِن کریں۔',
            'auth.expired'             => 'سیشن ختم ہو گیا۔ دوبارہ لاگ اِن کریں۔',
            'auth.current_wrong'       => 'موجودہ پاس ورڈ غلط ہے۔',
            'auth.must_change'         => 'جاری رکھنے سے پہلے پاس ورڈ تبدیل کریں۔',
            'auth.password_changed'    => 'پاس ورڈ تبدیل ہو گیا۔',
            'auth.logged_out'          => 'لاگ آؤٹ ہو گئے۔',
            'csrf.invalid'             => 'سیکیورٹی ٹوکن ختم ہو گیا۔ دوبارہ کوشش کریں۔',
            'error.forbidden'          => 'آپ کو اس کی اجازت نہیں۔',
            'error.not_found'          => 'ریکارڈ نہیں ملا۔',
            'error.route_not_found'    => 'نامعلوم API۔',
            'error.method'             => 'یہ طریقہ قابل قبول نہیں۔',
            'error.server'             => 'سرور میں خرابی۔ دوبارہ کوشش کریں۔',
            'error.bad_json'           => 'غلط درخواست۔',
            'error.constraint'         => 'یہ ریکارڈ دوسرے ڈیٹا سے منسلک ہے یا دہرا ہے۔',
            'error.db_not_configured'  => 'ڈیٹا بیس سیٹ نہیں۔ config.sample.php کو پرائیویٹ فولڈر میں config.php کے نام سے رکھیں۔',
            'error.db_unavailable'     => 'ڈیٹا بیس دستیاب نہیں۔ کچھ دیر بعد کوشش کریں۔',
            'setup.done'               => 'سیٹ اپ پہلے ہی مکمل ہے۔',
            'setup.bad_key'            => 'سیٹ اپ کی غلط ہے۔',
            'user.self_deactivate'     => 'آپ اپنا اکاؤنٹ غیر فعال یا حذف نہیں کر سکتے۔',
            'user.last_admin'          => 'کم از کم ایک فعال ایڈمن ہونا ضروری ہے۔',
            'role.admin_locked'        => 'ایڈمن کی اجازتیں تبدیل نہیں ہو سکتیں۔',
            'master.in_use'            => 'یہ ریکارڈ دوسرے ریکارڈز میں استعمال ہو رہا ہے، حذف نہیں ہو سکتا۔ اسے غیر فعال کر دیں۔',
            'unit.dimension_locked'    => 'آئٹمز یہ یونٹ استعمال کر رہے ہیں؛ اس کی قسم تبدیل نہیں ہو سکتی۔',
            'party.type_required'      => 'کم از کم ایک منتخب کریں: کسٹمر، سپلائر یا فیبرک مالک۔',
            'item.ink_unit'            => 'انک کے لیے حجم کا یونٹ (لیٹر یا ملی لیٹر) منتخب کریں۔',
            'item.fabric_unit'         => 'کپڑے کے لیے لمبائی یا وزن کا یونٹ منتخب کریں۔',
            'item.locked_by_stock'     => 'اس آئٹم کا اسٹاک موجود ہے؛ قسم اور یونٹ تبدیل نہیں ہو سکتے۔',
            'design.finished_item_type'=> 'تیار کپڑے کا آئٹم منتخب کریں۔',
            'design.duplicate_colour'  => 'یہ رنگ پہلے سے شامل ہے۔',
            'design.duplicate_item'    => 'یہ آئٹم پہلے سے شامل ہے۔',
            'design.ink_colour_mismatch' => 'یہ انک مختلف رنگ کی ہے۔',
            'design.basis_required'    => 'انک ملی لیٹر فی میٹر کے حساب کے لیے ضروری ہے۔',
            'design.bom_item_type'     => 'صرف پیپر، کیمیکل یا دیگر آئٹمز (انک، انک ٹیبل میں)۔',
            'upload.failed'            => 'اپ لوڈ ناکام۔ فائل دوبارہ منتخب کریں۔',
            'upload.too_large'         => 'فائل بہت بڑی ہے (زیادہ سے زیادہ 15 MB)۔',
            'upload.too_many_pixels'   => 'تصویر بہت بڑی ہے (زیادہ سے زیادہ 60 میگا پکسل)۔',
            'upload.bad_type'          => 'صرف JPG، PNG یا WEBP تصاویر۔',
            'upload.storage'           => 'فائل سرور پر محفوظ نہیں ہو سکی۔',
            'voucher.saved'            => 'واؤچر :no محفوظ ہو گیا۔',
            'voucher.cancelled'        => 'واؤچر :no منسوخ ہو گیا۔',
            'voucher.no_lines'         => 'کم از کم ایک لائن شامل کریں۔',
            'voucher.future_date'      => 'تاریخ آئندہ کی نہیں ہو سکتی۔',
            'voucher.not_editable'     => 'یہ واؤچر منسوخ ہے، تبدیل نہیں ہو سکتا۔',
            'stock.insufficient'       => ':warehouse:lot میں :item کا صرف :available :unit موجود ہے۔',
            'stock.would_go_negative'  => 'اجازت نہیں: :warehouse:lot میں :item کا اسٹاک منفی ہو جائے گا (بعد کے واؤچرز میں استعمال ہو چکا)۔',
            'stock.lot'                => 'لاٹ',
            'stock.lot_required'       => 'اس آئٹم کے لیے لاٹ نمبر ضروری ہے۔',
            'transfer.same_warehouse'  => 'سورس سے مختلف گودام منتخب کریں۔',
            'consumption.no_fabric'    => 'کپڑا یہاں جاری نہیں ہوتا (پروڈکشن واؤچر استعمال کریں)۔',
            'ink_load.not_ink'         => 'انک آئٹم منتخب کریں (لیٹر یا ملی لیٹر)۔',
            'ink_load.too_small'       => 'انک یونٹ کے لحاظ سے مقدار بہت کم ہے۔',
            'production.no_ink_item'   => 'رنگ :colour کا کوئی فعال انک آئٹم نہیں (انک ماسٹر میں شامل کریں)۔',
            'production.fabric_type'   => 'کپڑے کا آئٹم منتخب کریں۔',
            'production.grey_required' => 'گرے کپڑے کا آئٹم منتخب کریں۔',
            'production.no_conversion' => 'میٹر کو اس آئٹم کے یونٹ میں تبدیل نہیں کیا جا سکا (GSM اور چوڑائی درج کریں)۔',
            'production.no_fabric_line'=> 'کپڑا ہیڈر میں درج ہوتا ہے، میٹیریل لائن میں نہیں۔',
            'production.end_before_start' => 'اختتامی وقت آغاز سے پہلے ہے۔',
            'saved'                    => 'محفوظ ہو گیا۔',
            'deleted'                  => 'حذف ہو گیا۔',
        ],
    ];

    public static function set(string $lang): void
    {
        self::$lang = $lang === 'ur' ? 'ur' : 'en';
    }

    public static function current(): string
    {
        if (self::$lang === null) {
            $header = strtolower((string) Request::header('X-Lang'));
            self::$lang = $header === 'ur' ? 'ur' : 'en';
        }
        return self::$lang;
    }

    public static function t(string $key, array $vars = []): string
    {
        $text = self::MESSAGES[self::current()][$key] ?? self::MESSAGES['en'][$key] ?? $key;
        foreach ($vars as $name => $value) {
            $text = str_replace(':' . $name, (string) $value, $text);
        }
        return $text;
    }
}
